# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addmachine.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addmachine(object):
    def setupUi(self, addmachine):
        addmachine.setObjectName("addmachine")
        addmachine.resize(598, 469)
        self.port_label = QtWidgets.QLabel(addmachine)
        self.port_label.setGeometry(QtCore.QRect(70, 120, 67, 17))
        self.port_label.setObjectName("port_label")
        self.password_line = QtWidgets.QLineEdit(addmachine)
        self.password_line.setGeometry(QtCore.QRect(410, 80, 151, 25))
        self.password_line.setObjectName("password_line")
        self.host_label = QtWidgets.QLabel(addmachine)
        self.host_label.setGeometry(QtCore.QRect(70, 80, 67, 17))
        self.host_label.setObjectName("host_label")
        self.name_line = QtWidgets.QLineEdit(addmachine)
        self.name_line.setGeometry(QtCore.QRect(150, 40, 151, 25))
        self.name_line.setObjectName("name_line")
        self.host_line = QtWidgets.QLineEdit(addmachine)
        self.host_line.setGeometry(QtCore.QRect(150, 80, 151, 25))
        self.host_line.setObjectName("host_line")
        self.password_label = QtWidgets.QLabel(addmachine)
        self.password_label.setGeometry(QtCore.QRect(330, 80, 67, 17))
        self.password_label.setObjectName("password_label")
        self.key_line = QtWidgets.QLineEdit(addmachine)
        self.key_line.setGeometry(QtCore.QRect(150, 170, 221, 25))
        self.key_line.setMaxLength(32765)
        self.key_line.setReadOnly(True)
        self.key_line.setObjectName("key_line")
        self.user_label = QtWidgets.QLabel(addmachine)
        self.user_label.setGeometry(QtCore.QRect(330, 40, 81, 17))
        self.user_label.setObjectName("user_label")
        self.user_line = QtWidgets.QLineEdit(addmachine)
        self.user_line.setGeometry(QtCore.QRect(410, 40, 151, 25))
        self.user_line.setObjectName("user_line")
        self.key_label = QtWidgets.QLabel(addmachine)
        self.key_label.setGeometry(QtCore.QRect(70, 170, 31, 21))
        self.key_label.setObjectName("key_label")
        self.browse_button = QtWidgets.QPushButton(addmachine)
        self.browse_button.setGeometry(QtCore.QRect(380, 170, 89, 25))
        self.browse_button.setObjectName("browse_button")
        self.clear_button = QtWidgets.QPushButton(addmachine)
        self.clear_button.setGeometry(QtCore.QRect(480, 420, 89, 25))
        self.clear_button.setObjectName("clear_button")
        self.port_line = QtWidgets.QLineEdit(addmachine)
        self.port_line.setGeometry(QtCore.QRect(150, 120, 71, 25))
        self.port_line.setObjectName("port_line")
        self.configure_button = QtWidgets.QPushButton(addmachine)
        self.configure_button.setGeometry(QtCore.QRect(190, 230, 89, 25))
        self.configure_button.setObjectName("configure_button")
        self.add_button = QtWidgets.QPushButton(addmachine)
        self.add_button.setGeometry(QtCore.QRect(380, 420, 89, 25))
        self.add_button.setObjectName("add_button")
        self.tunnel_label = QtWidgets.QLabel(addmachine)
        self.tunnel_label.setGeometry(QtCore.QRect(70, 230, 101, 21))
        self.tunnel_label.setObjectName("tunnel_label")
        self.name_label = QtWidgets.QLabel(addmachine)
        self.name_label.setGeometry(QtCore.QRect(70, 40, 67, 17))
        self.name_label.setObjectName("name_label")
        self.portforward_check = QtWidgets.QCheckBox(addmachine)
        self.portforward_check.setGeometry(QtCore.QRect(70, 280, 131, 23))
        self.portforward_check.setTristate(False)
        self.portforward_check.setObjectName("portforward_check")
        self.localport_line = QtWidgets.QLineEdit(addmachine)
        self.localport_line.setEnabled(False)
        self.localport_line.setGeometry(QtCore.QRect(180, 350, 71, 25))
        self.localport_line.setObjectName("localport_line")
        self.localhost_line = QtWidgets.QLineEdit(addmachine)
        self.localhost_line.setEnabled(False)
        self.localhost_line.setGeometry(QtCore.QRect(180, 320, 71, 25))
        self.localhost_line.setObjectName("localhost_line")
        self.localhost_label = QtWidgets.QLabel(addmachine)
        self.localhost_label.setGeometry(QtCore.QRect(70, 320, 81, 20))
        self.localhost_label.setObjectName("localhost_label")
        self.localport_label = QtWidgets.QLabel(addmachine)
        self.localport_label.setGeometry(QtCore.QRect(70, 350, 81, 20))
        self.localport_label.setObjectName("localport_label")
        self.remoteport_label = QtWidgets.QLabel(addmachine)
        self.remoteport_label.setGeometry(QtCore.QRect(70, 410, 91, 20))
        self.remoteport_label.setObjectName("remoteport_label")
        self.remotehost_label = QtWidgets.QLabel(addmachine)
        self.remotehost_label.setGeometry(QtCore.QRect(70, 380, 91, 20))
        self.remotehost_label.setObjectName("remotehost_label")
        self.remotehost_line = QtWidgets.QLineEdit(addmachine)
        self.remotehost_line.setEnabled(False)
        self.remotehost_line.setGeometry(QtCore.QRect(180, 380, 71, 25))
        self.remotehost_line.setObjectName("remotehost_line")
        self.remoteport_line = QtWidgets.QLineEdit(addmachine)
        self.remoteport_line.setEnabled(False)
        self.remoteport_line.setGeometry(QtCore.QRect(180, 410, 71, 25))
        self.remoteport_line.setObjectName("remoteport_line")
        self.local_forwarding = QtWidgets.QRadioButton(addmachine)
        self.local_forwarding.setEnabled(False)
        self.local_forwarding.setGeometry(QtCore.QRect(300, 320, 151, 21))
        self.local_forwarding.setObjectName("local_forwarding")
        self.remote_forwarding = QtWidgets.QRadioButton(addmachine)
        self.remote_forwarding.setEnabled(False)
        self.remote_forwarding.setGeometry(QtCore.QRect(300, 350, 161, 23))
        self.remote_forwarding.setObjectName("remote_forwarding")

        self.retranslateUi(addmachine)
        QtCore.QMetaObject.connectSlotsByName(addmachine)
        addmachine.setTabOrder(self.name_line, self.host_line)
        addmachine.setTabOrder(self.host_line, self.port_line)
        addmachine.setTabOrder(self.port_line, self.user_line)
        addmachine.setTabOrder(self.user_line, self.password_line)
        addmachine.setTabOrder(self.password_line, self.key_line)
        addmachine.setTabOrder(self.key_line, self.browse_button)
        addmachine.setTabOrder(self.browse_button, self.configure_button)
        addmachine.setTabOrder(self.configure_button, self.portforward_check)
        addmachine.setTabOrder(self.portforward_check, self.add_button)
        addmachine.setTabOrder(self.add_button, self.clear_button)
        addmachine.setTabOrder(self.clear_button, self.localhost_line)
        addmachine.setTabOrder(self.localhost_line, self.localport_line)
        addmachine.setTabOrder(self.localport_line, self.remotehost_line)
        addmachine.setTabOrder(self.remotehost_line, self.remoteport_line)
        addmachine.setTabOrder(self.remoteport_line, self.local_forwarding)
        addmachine.setTabOrder(self.local_forwarding, self.remote_forwarding)

    def retranslateUi(self, addmachine):
        _translate = QtCore.QCoreApplication.translate
        addmachine.setWindowTitle(_translate("addmachine", "Add a Machine"))
        self.port_label.setText(_translate("addmachine", "SSH Port"))
        self.host_label.setText(_translate("addmachine", "Host/IP"))
        self.password_label.setText(_translate("addmachine", "Password"))
        self.user_label.setText(_translate("addmachine", "Username"))
        self.key_label.setText(_translate("addmachine", "Key"))
        self.browse_button.setText(_translate("addmachine", "Browse"))
        self.clear_button.setText(_translate("addmachine", "Clear"))
        self.configure_button.setText(_translate("addmachine", "Configure"))
        self.add_button.setText(_translate("addmachine", "Add"))
        self.tunnel_label.setText(_translate("addmachine", "SSH Tunneling"))
        self.name_label.setText(_translate("addmachine", "Name"))
        self.portforward_check.setText(_translate("addmachine", "Port Forward?"))
        self.localhost_label.setText(_translate("addmachine", "Local Host"))
        self.localport_label.setText(_translate("addmachine", "Local Port"))
        self.remoteport_label.setText(_translate("addmachine", "Remote Port"))
        self.remotehost_label.setText(_translate("addmachine", "Remote Host"))
        self.local_forwarding.setText(_translate("addmachine", "Local Forwarding"))
        self.remote_forwarding.setText(_translate("addmachine", "Remote Forwarding"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addmachine = QtWidgets.QDialog()
    ui = Ui_addmachine()
    ui.setupUi(addmachine)
    addmachine.show()
    sys.exit(app.exec_())
